# Generated by Django 5.0.3 on 2024-04-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=50)),
                ('message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'MyModel',
                'verbose_name_plural': 'MyModels',
            },
        ),
    ]
