# Generated by Django 5.0.3 on 2024-04-20 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoforms', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModel',
            new_name='Student',
        ),
    ]
